#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_REGEX="^(fix|feat|ui|component|package|add|docs|style|refactor|test|chore|app|build|deps|dev|infra|change|remove|update|revert): .+"
ERROR_MSG="Commit message should start with fix:, feat:, ui:, component:, etc."

if ! grep -qE "$COMMIT_REGEX" "$1"; then
  echo "$ERROR_MSG" >&2
  exit 1
fi
